### PR TITLE
Solve conflict2 (#)

### PR DESCRIPTION
**Pull request by MahmoudShalma**
Conflicts are solved.

### CODE REVIEW

**Comment by Hossam-Tarek** [comment]
Why you are solving the conflict with a new pull request that's unrealistic, now I'm kinda confused about what pull request I'm gonna delete and what I'm gonna merge. 

And by the way, if you have a conflict in an existing pull request you don't need to solve it in a new pull request. Just solve it on your local machine, then push those changes to your fork it'll update the pull request automatically and solve the conflict by using this command on your local machine`git push origin name-of-your-branch`.

**Comment by ahmed-fawzy-metwally** [comment]
Those conflicts were not as easy as you see.
We do what you see solve conflict and push this to a branch of Mahmoud ob GitHub but nothing was solved except ``` style.css ```
We work on it from 2:30 am to 4:30  am.

**Comment by Hossam-Tarek** [comment]
Great job. and thank you for your effort.

**Comment by ahmed-fawzy-metwally** [comment]
Thanks a lot.

**Pull request merged**
